apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-jacoco-agent
  labels:
    app: init-jacoco-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-jacoco-agent
  template:
    metadata:
      labels:
        app: init-jacoco-agent
    spec:
      containers:
        - name: init-jacoco-agent
          env:
            - name: INIT_JACOCO_AGENT_IMG
              value: os-harbor-svc.default.svc.cloudos:443/helm/h3ccloud/jacocoagent:0.8.10
          image:
          imagePullPolicy: Always
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -protect_ns=kube-system
            - -protect_ns=kube-public
            - -protect_ns=default
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: init-jacoco-certs
