apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-sw-agent
  labels:
    app: init-sw-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-sw-agent
  template:
    metadata:
      labels:
        app: init-sw-agent
    spec:
      containers:
        - name: init-sw-agent
          env:
            - name: INIT_SW_AGENT_IMG
              value: securityneo/skywalking:java-agent-8.12
          image:
          imagePullPolicy: Always
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: init-sw-certs
