apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: init-jacoco-agent
  labels:
    app: init-jacoco-agent
webhooks:
  - name: init-jacoco-agent.neo.com
    admissionReviewVersions: ["v1","v1beta1"]
    sideEffects: None
    clientConfig:
      service:
        name: init-jacoco-agent-svc
        namespace: default
        path: "/api/v1/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE","UPDATE"]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","statefulsets"]
    namespaceSelector:
      matchLabels:
        enable-jacoco-agent.neo.com/mutate: "true"
    
